from scumjournaluitesting.devicemetrics.device_metrics import new_device, DeviceName

devices = [
    new_device(
        device=DeviceName.iPhone_SE,
        width=320,
        height=568,
        pixel_ratio=2
    ),
    new_device(
        device=DeviceName.iPhone_XR,
        width=414,
        height=896,
        pixel_ratio=2
    ),
    new_device(
        device=DeviceName.iPhone_12_Pro,
        width=390,
        height=844,
        pixel_ratio=3
    ),
    new_device(
        device=DeviceName.Pixel_5,
        width=393,
        height=851,
        pixel_ratio=2.8
    ),
    new_device(
        device=DeviceName.Samsung_Galaxy_S8plus,
        width=360,
        height=740,
        pixel_ratio=4
    ),
    new_device(
        device=DeviceName.Samsung_Galaxy_S20_Ultra,
        width=412,
        height=869,
        pixel_ratio=3.5
    ),
    new_device(
        device=DeviceName.iPad_Air,
        width=768,
        height=1024,
        pixel_ratio=2
    ),
    new_device(
        device=DeviceName.iPad_Mini,
        width=768,
        height=1024,
        pixel_ratio=1
    ),
    new_device(
        device=DeviceName.Surface_Pro_7,
        width=1366,
        height=768,
        pixel_ratio=1
    ),
    new_device(
        device=DeviceName.Surface_Duo,
        width=540,
        height=720,
        pixel_ratio=2.1
    ),
    new_device(
        device=DeviceName.Galaxy_Fold,
        width=280,
        height=653,
        pixel_ratio=2.625
    ),
    new_device(
        device=DeviceName.Samsung_Galaxy_A51slash71,
        width=360,
        height=760,
        pixel_ratio=2
    )
]
